dist: trusty
sudo: false
language: java
jdk:
  - openjdk11
before_install:
install: true
script:
  - ./mvnw clean install -P-docker
cache:
  directories:
    - $HOME/.m2
before_cache:
  - rm -rf $HOME/.m2/repository/org/geonetwork-opensource