# Project information
site_name: GeoNetwork Opensource Microservices
site_description: GeoNetwork Opensource Microservices.
site_dir: target/html
site_url: https://docs.geonetwork-opensource.org/

# Repository
repo_name: geonetwork-microservices
repo_url: https://github.com/geonetwork/geonetwork-microservices
edit_uri: edit/main/docs/manual/docs

# Copyright
copyright: Copyright &copy; 2024 FAO-UN and others

extra_css:
  - assets/stylesheets/extra.css

# Configuration
theme:
  name: material
  language: en
  custom_dir: overrides
  logo: assets/images/geonetwork-logo.svg
  favicon: assets/images/geonetwork-logo.png
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - toc.follow
    - navigation.tracking
    - navigation.top
    - navigation.tabs
    - navigation.prune
    - navigation.indexes
    - navigation.footer
    - header.autohide
    - content.tabs.link
    - content.code.copy
    - content.action.view
    - content.action.edit
    - announce.dismiss

# Plugins - install using: pip3 install -r requirements.txt
plugins:
  - exclude:
      glob:
        - annexes/gallery/bin/README.md
  - i18n:
      docs_structure: suffix
      reconfigure_material: true
      languages:
        - locale: en
          name: English
          build: true
          default: true
          site_name: 'GeoNetwork MicroServices OpenSource'
        - locale: fr
          name: Français
          build: !ENV [FRENCH,true]
          site_name: 'GeoNetwork MicroServices OpenSource'
          site_description: Catalogue GeoNetwork pour répertorier, rechercher et examiner les enregistrements.
          nav_translations:
            Home: Home
            Search: Search
            Record: Record
            Map: Map
  - search

# Customizations
extra:
  version:
    provider: mike
    default: stable
    alias: true
  homepage: https://geonetwork-opensource.org/
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/geonetwork
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/_/geonetwork
    - icon: geonetwork/logo_bw
      link: https://geonetwork-opensource.org/
      name: GeoNetwork Website

# For use with --strict to produce failures on build warnings
validation:
  nav:
    omitted_files: warn
    not_found: warn
    absolute_links: warn
  links:
    not_found: warn
    absolute_links: warn
    unrecognized_links: warn

# Extensions
# - These are carefully chosen to work with pandoc markdown support for whole document translation
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - md_in_html

# Page tree
nav:
  - 'GeoNetwork MicroServices': index.md
  - 'OGCAPI-Records':
    - ogcapi/index.md
    - ogcapi/landingpage.md
    - ogcapi/conformance.md
    - ogcapi/openapi.md
    - ogcapi/record-collections.md
    - ogcapi/record-collection.md
    - ogcapi/records.md
    - ogcapi/record.md
 
