spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gn
    username: www-data
    password: www-data
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    jpa.generate-ddl: true
    jpa.hibernate.ddl-auto: update